apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: linkding
  namespace: argocd
spec:
  description: Linkding Bookmark Manager Project
  sourceRepos:
  - 'https://github.com/melvinlee/gitops-argocd.git'
  destinations:
  - namespace: linkding-dev
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  namespaceResourceBlacklist: []
