apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nginx
  namespace: argocd
spec:
  description: Nginx Canary Deployment Project
  sourceRepos:
  - 'https://github.com/melvinlee/gitops-argocd.git'
  destinations:
  - namespace: nginx-dev
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  namespaceResourceBlacklist: []