apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: oracle-prod

resources:
  - ../../base

patchesStrategicMerge:
  - oracle-patches.yaml

commonLabels:
  environment: production