apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: oracle-dev

resources:
  - ../../base

patchesStrategicMerge:
  - oracle-patches.yaml

commonLabels:
  environment: development