apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: oracle
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"