apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollout.yaml
  - service.yaml

commonLabels:
  app: nginx
  app.kubernetes.io/name: nginx
  app.kubernetes.io/part-of: nginx-canary
  app.kubernetes.io/managed-by: argocd