apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

commonLabels:
  app: linkding
  app.kubernetes.io/name: linkding
  app.kubernetes.io/part-of: linkding