apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - oracle.yaml
  - sqlplus-pod.yaml

commonLabels:
  app.kubernetes.io/part-of: oracle-database
  app.kubernetes.io/managed-by: argocd