apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: linkding-dev

patchesStrategicMerge:
  - linkding-patches.yaml

commonLabels:
  environment: development
  app: linkding