apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: linkding
        image: sissbruecker/linkding:1.17.0
        env:
        - name: LD_DEBUG
          value: "True"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        # Change the volume mount configuration for dev
        volumeMounts: []
      # Remove the volumes section for dev
      volumes: []
---
# Null patch to remove the PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data
$patch: delete